spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/p6_bdd
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:

  level:
    org:
      springframework:
        security: info
spring.datasource.type: org.springframework.jdbc.datasource.SimpleDriverDataSource


